M48
; DRILL file {KiCad 6.0.8-f2edbf62ab~116~ubuntu22.04.1} date Tue 10 Jan 2023 04:41:10 PM PST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-01-10T16:41:10-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.8-f2edbf62ab~116~ubuntu22.04.1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0130
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0394
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0960
%
G90
G05
T1
X1.7233Y-2.0663
T2
X2.55Y-1.95
X2.55Y-2.05
T3
X2.0Y-1.5
X2.0Y-2.5
T0
M30
